# Generated by Django 4.2.7 on 2024-08-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
