# Generated by Django 4.2.7 on 2024-08-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
