# Generated by Django 4.2.7 on 2024-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comment_count',
        ),
    ]
