# Generated by Django 5.1.9 on 2025-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
