# Generated by Django 4.2.7 on 2024-08-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
