# Generated by Django 4.2.7 on 2024-08-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_remove_comment_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
